### ISSUE TITLE
SPDX coverage from FOSSology project

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#1309]
### Description

This is a meta issue for summarizing what are current not supported corners of the SPDX standard not covered by FOSSology so far. It shall bring transparency -- please fee free to add points to this. 

### Individual Issues Covered by the SPDX spec

- [ ] SPDX Comments: https://github.com/fossology/fossology/issues/645
- [ ] Import tag_value SPDX (not RDF ony), file matching  https://github.com/fossology/fossology/issues/669
- [ ] Support for full SPDX license expressions https://github.com/fossology/fossology/issues/687
- [ ] no URL encoding of SPDX license names https://github.com/fossology/fossology/issues/747
- [ ] individual license Ids in FOSSology are stupid https://github.com/fossology/fossology/issues/748

### Individual Issues around SPDX

- [ ] get SPDX https://github.com/fossology/fossology/issues/592

**Comment by silverhook** [comment]
Relevant also:

- Change Nomos’ PHP-2.0.2 license (name) to PHP-2.02 #1213
