### ISSUE TITLE
Migrate from Travis to Github Actions

### ISSUE THREAD

**Issue by NishealJ** [fossology/fossology#1913]
### Description
Fossology currently uses Travis, but moving into GitHub action will be more convenient and versatile for building+running tests.
Read more at, https://github.com/fossology/fossology/wiki/Google-Summer-of-Code-Proposals-2021#migrate-from-travis-to-github-actions

The list of jobs that has to be migrated from Travis to Github Actions are:

- [x] Syntax Check (#1919)
- [x] Static Code Analysis (#1919)
- [x] Copy/Paste Detector (#1919)
- [x] PHP Codesniffer (#1919)
- [ ] Docker Tests
- [x] Docker builds (#2076)
- [ ] C/C++ agent tests
- [ ] PHPUnit tests
- [x] GitHub Page Release (#1917)
- [ ] Implementing Caching in workflows
- [ ] Implement source install (see #207)

#### Steps followed and expected result
https://github.com/fossology/fossology/actions

**Comment by GMishx** [comment]
Everything was moved eventually. Thank you for starting it! Closing the issue as done.
