### ISSUE TITLE
feature(spdx2Import): add new agent to import SPDX2 reports

### ISSUE THREAD

**Issue by maxhbr** [fossology/fossology#669]
# spdx2Import

This agent should be able to upload an SPDX2 RDF file (later tag:value support might be added) and add the contained information as scanner findings / conclusions to an chosen upload.
This could be used to add license information from other sources or to review/verify reports.
## Implementation

A first version of this agent is implemented in the branch https://github.com/fossology/fossology/tree/dev/addSPDX2ImportAgent.
As this RDF parser this implementation uses EasyRDF which is licensed under BSD3. 
## TODOs:
- [x] add ui to upload a report
- [x] parse the RDF file
- [x] compare files in report to files in the db
- [x] import license information for matching files
- [x] import copyright information for matching files
- [x] show scanner findings in license-browser view (and others)
- [x] include the results into the clearing status information
- [x] make the uploaded report downloadeable
- [x] add a new type of clearing decission (**byImport**) and use them to import concluded licenses from the report (this should be optional)
- [ ] show copyright informations in copyright ui
- [x] show clearing information of type **byImport** in the license browser
- [x] create license candidates for licenses, which are not yet in the DB?
- [ ] add this agent to the supported agent for exporting (i.e. SPDX, DEB5, readmeOSS, ...)
## To discuss
- [x] compare entrys by **filename and hashes** or just **hashes**?
- [x] parse tag:value SPDX files
- [x] parse debian copyright?

**Comment by maximilianhuber** [comment]
## More Questions
* Add option to conclude license, if finding matches another scanner finding?
* Add as an alternative a list of existing uploads to choose from?

**Comment by maximilianhuber** [comment]
@mcjaeger: the problem you had with the menu entries should be fixed.

The import can now be found in the following two places:
![screen_2016-08-29_13-07-26](https://cloud.githubusercontent.com/assets/1187050/18049621/b8f13860-6de9-11e6-82fe-2a3b0a949932.png)
and (in the browse view)
![screen_2016-08-29_13-12-05](https://cloud.githubusercontent.com/assets/1187050/18049757/6db413e4-6dea-11e6-9fee-abf905034085.png)

(one of them can be removed in https://github.com/fossology/fossology/blob/b7097f46dbd1d489367a46b146ef0e9b3bcc80fb/src/spdx2Import/ui/SpdxTwoImportPlugin.php#L49-L50)

**Comment by mcjaeger** [comment]
I propose to focus on the initial use case which is review. Let's put import and then export again in another use case, which is SPDX correction or SPDX enhancement.

**Comment by mcjaeger** [comment]
new licenses from the database must be pulled in as candidates. If put straight forward to the main database set, they would alter the scan result of monk for all users of the server - maybe unwanted, because the extracted text from the imported SPDX file is not a valid license text. As candidates, the user can decide whether to promote them to a regular license.

**Comment by mstair** [comment]
Anything special I need to do in the build to activate? I am not seeing the plugin after a make install.

**Comment by maximilianhuber** [comment]
Have you used the corresponding branch for building? The branch corresponding to this issue is https://github.com/fossology/fossology/tree/dev/addSPDX2ImportAgent

**Comment by mstair** [comment]
Yes, from that branch using these instructions. Let me start with a clean VM. Thanks for the response.

https://github.com/fossology/fossology/wiki/Install-from-Source

**Comment by mcjaeger** [comment]
(from discussion) Handling of Licenses, following cases:

1. SPDX Id in SPDX file -> SPDX Id license is in Fossology 
  e.g. "GPL-2.0"
  -> straight import
  -> no problem

2. SPDX Id mit prefix "LicenseRef-" and hash suffix (custom text in fossology)
  e.g. "LicenseRef-GPL-2.0-4738298292ababa67262"
  -> import as custom text

3. Prefix "LicenseRef-" with Non-SPDX Fossology license from license ref and candidates
  e.g. "LicenseRef-BSD"
  -> Extract license short name, in this case "BSD"
  -> compare license text from fossololgy
  -> if texts match, straight import
  -> if not, then license candidate with short name plus hash
  -> hash can be used to identify same

4. Prefix "LicenseRef-" with (completely) unknown continuation
  e.g. "LicenseRef-Michaelsnewlicense"
  -> import as candidate

**Comment by maximilianhuber** [comment]
@mcjaeger the `AdminLicenseCandidate.php`-page uses one-shot-monk for suggesting licenses related to an ID:
```php
[...]
  private function suggestLicenseId($str){
    /* @var $monkOneShotPlugin \Fossology\Monk\UI\Oneshot */
    $monkOneShotPlugin = plugin_find("oneshot-monk");

    if (null !== $monkOneShotPlugin)
    {
      return $monkOneShotPlugin->scanMonkRendered($str);
    } else
    {
      return array(array(), $str);
    }
  }
[...]
```
I am not sure whether this is an option for us here.

**Comment by mcjaeger** [comment]
@maxhbr yes that is even a similar case (manually added candidate licences comparison is similar to imported candidate licenses)

**Comment by mcjaeger** [comment]
@maxhbr any update on the " compare entrys by filename and hashes or just hashes?" part? I am not sure if I can contribute any operational experience.

**Comment by maxhbr** [comment]
I think the current implementation works fine. It compares by filename and then by hash or als fallback only via hash. So this discussion ponit could be closed.

Implementation:
https://github.com/fossology/fossology/blob/beeadb341c85306247653de8881cbff3748d4291/src/reportImport/agent/ReportImportAgent.php#L167-L193

**Comment by shaheemazmalmmd** [comment]
ReportImport Agent solves this issue. closing
