### ISSUE TITLE
Add functional tests - collector issue

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#776]
Collected issues for adding a functional tests, reopening, because it does not make sense to have a single issue for each functional test - referring to the original issue with link for your reference:

- [ ] #177 Paul Holland 2012/06/15 Add functional tests for fo-cleanold
- [ ] #175 Paul Holland 2012/06/15 Add functional tests for fo_cli: "The cli is tested extensively during the scheduler's functional tests. This is because the cli is how the testing harness checks that the scheduler is in a valid state."
- [ ] #174 Paul Holland 2012/06/15 Add unit tests for fo_cli: "I doubt that unit tests would be of benefit for fo_cli. This is such a simple program that the functional tests should be sufficient. I'm not going to set this to resolved though as someone else should confirm that this is correct."
- [ ] #173 Paul Holland 2012/06/15 Add functional tests for fossjobs
- [ ] #171 Paul Holland 2012/06/15 Add functional tests for cp2foss
- [ ] #169 Paul Holland 2012/06/15 Add functional testing/automation for checking system dependencies: "Add tests to check for the following dependencies: PostgreSQL, Apache httpd, Glib ..."
- [ ] #168 Paul Holland 2012/06/15 Add functional tests for Common UI modules (Vincent)
- [ ] #166 Paul Holland 2012/06/15 Add functional tests for Common UI modules (Alex): "Add tests for the following modules: common-scheduler.php, common-sysconfig.php"
- [ ] #164 Paul Holland 2012/06/15 Add functional tests for Common UI modules (Larry): "Add tests for the following modules:common-cli.php, common-dir.php, common-folders.php, common-menu.php, common-ui.php"Add functional tests for Common UI modules #162
- [ ] #162 Paul Holland 2012/06/15 Add functional tests for Common UI modules: "Add tests for the following modules: common-active.php, common-agents.php, common-cache.php, common-buckets.php, common-compare.php, common-db.php, common-job.php, common-license-file.php,common.php, common-plugin.php, common-repo.php, common-tags.php, bootstrap.php"
- [ ] #160 Paul Holland 2012/06/15 Add functional tests for repremove
- [ ] #158 Paul Holland 2012/06/15 Add functional tests for repcopyin 
- [ ] #156 Paul Holland 2012/06/15 Add functional tests for sqlCopy
- [ ] #150 Paul Holland 2012/06/15 Add functional tests for Admin 
- [ ] #149 Paul Holland 2012/06/15 Add functional tests for User Permissions #149
- [ ] #147 Paul Holland 2012/06/15 Add functional tests for Organize UI tasks: "HI paul, sorry, I did not capture what do you mean 'Add functional tests for Organize UI tasks', you mean adding UI-Based tests into functional test automation framework to confirm whether the legacy functions of fossology or new check in work or not, correct?
- [ ] if yes, it is a pity, I can not start this task, till now, our web-based test framework does not work, mary is investigating test framework, perhaps she can give us some suggestion."
- [ ] #145 Paul Holland 2012/06/15 Add functional tests for Browse UI tasks 
- [ ] #143 Paul Holland 2012/06/15 Add functional tests for Search UI tasks 
- [ ] #141 Paul Holland 2012/06/15 Add functional tests for Jobs UI tasks
- [ ] #139 Paul Holland 2012/06/15 Add functional tests for Upload UI tasks
- [ ] #138 Paul Holland 2012/06/15 Add unit tests for Upload UI tasks: "Bumping to iteration 6., Set rank to 2 (is this correct?), mary, how to add unit tests for Upload UI tasks, do you have any suggestions? thanks, I have no idea for now., Unit testing Upload UI are part of the larger task identified in #2505 "Need to provide samples of good unit and functional tests.", Resetting rank back to 6 so it is prioritized correctly with the other wor"
- [ ] #137 Paul Holland 2012/06/15 Add functional tests for Homepage UI tasks
- [ ] #135 Paul Holland 2012/06/15 Add functional tests for Wget_Agent
- [ ] #134 Paul Holland 2012/06/15 Add functional tests for Package Agent 
- [ ] #131 Paul Holland 2012/06/15 Add functional tests for Copyright agent 
- [ ] #130 Paul Holland 2012/06/15 Add functional tests for RESTful UI for PTS 
- [ ] #128 Paul Holland 2012/06/15 Add functional tests/automation for cluster testing 
- [ ] #127 Paul Holland 2012/06/15 Add functional tests/automation for migration testing 
- [ ] #126 Paul Holland 2012/06/15 Add functional tests for Tagging 
- [ ] #124 Paul Holland 2012/06/15 Add functional tests for UI tasks 
- [ ] #122 Paul Holland 2012/06/15 Add functional tests for NomosDiff
- [ ] #120 Paul Holland 2012/06/15 Add functional tests for BucketsDiff
- [ ] #118 Paul Holland 2012/06/15 Add functional tests for Nomos
- [ ] #116 Paul Holland 2012/06/15 Add functional tests for Buckets
- [ ] #114 Paul Holland 2012/06/15 Add functional tests for Adj2Nest

**Comment by shaheemazmalmmd** [comment]
We have already implemented tests for most of the functional features. needs a re look
