### ISSUE TITLE
Add unit tests - collector issue

### ISSUE THREAD

**Issue by mcjaeger** [fossology/fossology#777]
Listing all tests for unit tests. All issues were created by Paul Holland on 15th of May in 2012. Original issues were closed since it does not make sense for issue / backlog organisation to have issues for every single unit test. 

- [ ] #178 Add unit tests for schema_export 
- [ ] #176 Add unit tests for fo-cleanold 
- [ ] #172 Add unit tests for fossjobs 
- [ ] #170 Add unit tests for cp2foss 
- [ ] #167 Add unit tests for Common UI Modules (Vincent)  
- [ ] #165 Add unit tests for Common UI Modules (Alex) 
- [ ] #163 Add unit tests for Common UI Modules (Larry)
- [ ] #161 Add unit tests for Common UI Modules (Dan)
- [ ] #159 Add unit tests for repremove
- [ ] #157 Add unit tests for repcopyin
- [ ] #155 Add unit tests for sqlCopy
- [ ] #154 Add unit tests for libfossdb
- [ ] #153 Add unit tests for libfossscheduler
- [ ] #152 Add unit tests for libfossrepo
- [ ] #151 Add unit tests for libfossagent 
- [ ] #148 Add unit tests for User Permissions
- [ ] #146 Add unit tests for Organize UI tasks
- [ ] #144 Add unit tests for Browse UI tasks
- [ ] #142 Add unit tests for Search UI tasks
- [ ] #140 Add unit tests for Jobs UI tasks
- [ ] #136 Add unit tests for Homepage UI tasks
- [ ] #133 Add unit tests for Package Agent
- [ ] #132 Add unit tests for Delagent
- [ ] #129 Add unit tests for the RESTful UI for PTS 
- [ ] #125 Add unit tests for Tagging
- [ ] #123 Add unit tests for Admin UI tasks
- [ ] #121 Add unit tests for NomosDiff
- [ ] #119 Add unit tests for BucketsDiff
- [ ] #117 Add unit tests for Nomos

**Comment by shaheemazmalmmd** [comment]
Need re-check as most of the test cases are implemented.
